### ISSUE TITLE
Server - Add completion for keywords in a schema

### ISSUE THREAD

**Issue by jdesrosiers** [hyperjump-io/json-schema-language-tools#11]
When creating a property inside a schema, suggest dialect appropriate keywords for auto-completion.

* [ ] Suggestions should only appear in a schema context. (Ex: The value of the `properties` keyword is an object, but it's not a schema and shouldn't suggest keywords.)
* [ ] Only suggest keywords appropriate for the for current dialect. (Ex: Don't suggest `definitions` in 2020-12.) (Hint: Use `@hyperjump/json-schema` to determine what keywords are appropriate for each dialect.)
* [ ] Be sure to correctly handle embedded schemas where the dialect changes.

**Comment by Min2who** [comment]
Hii @jdesrosiers can i work on this

**Comment by utnim2** [comment]
> @utnim2 Do you have a partner?

@ibishal has agreed (we have talked on slack)

**Comment by jdesrosiers** [comment]
Great! Make sure to create a create a group DM in slack and include me. Remember I'm part of your team as well.

@utnim2, you've been assigned. @ibishal, Github won't let me assign you unless you've commented on the issue. Please comment a quick "hello" or something so I can assign you too.

**Comment by ibishal** [comment]
> Great! Make sure to create a create a group DM in slack and include me. Remember I'm part of your team as well.
> 
> @utnim2, you've been assigned. @ibishal, Github won't let me assign you unless you've commented on the issue. Please comment a quick "hello" or something so I can assign you too.

ok @jdesrosiers
