### ISSUE TITLE
Server - Implement goto definition

### ISSUE THREAD

**Issue by jdesrosiers** [hyperjump-io/json-schema-language-tools#19]
Implement "goto definition" jump to the schema a reference refers to.

Depends on: #7

**Comment by lmgyuan** [comment]
Hi @jdesrosiers I am having difficulty finding partners for this issue. May I ask whether I should work on this by myself? Thanks in advance!

**Comment by LordRona** [comment]
Hello @jdesrosiers Please I have downloaded the project and installed all dependencies but I really don't know how to run the project. From the README.MD files I can't comprehend clearly how to go about it, please HELP.

**Comment by LordRona** [comment]
And I will really like to have someone with whom I can pair with in working in this exciting task.

**Comment by jdesrosiers** [comment]
@lmgyuan @LordRona The dependent issue makes this a bad choice at this time. I'll remove the label. I just created #29. You two could team up and take that one. If you want to do that, I need both of you to comment on the issue so I can assign you.

**Comment by jdesrosiers** [comment]
@LordRona I suggest going through [this tutorial](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) first. It includes better instructions on how to run the language server than my README and the approach is the same as this project.
