### ISSUE TITLE
Server - Hover information

### ISSUE THREAD

**Issue by jdesrosiers** [hyperjump-io/json-schema-language-tools#22]
Use the `description` annotation to provide hover text for schema keywords.

Note: `description`s don't currently exist. We'll have to augment the meta-schemas we use with appropriate descriptions.

**Comment by DarhkVoyd** [comment]
Hey @jdesrosiers,
We, @mabagoury and @darhkvoyd, have partnered up to collaborate on this issue. We're starting with getting familiar with the codebase and getting a better understanding by reading relevant documentation and studying existing language servers written in TypeScript such as `tsserver`.

**Comment by jdesrosiers** [comment]
Sound good. @DarhkVoyd, you've been assigned. @mabagoury, can you comment a quick "hello" or whatever. Github won't let me assign you to the issue unless you've commented on the issue.

**Comment by mabagoury** [comment]
Sure. Let's do it.

**Comment by mabagoury** [comment]
@jdesrosiers Sure. Let's do it.
