### ISSUE TITLE
Server - Add a config to define what files should be treated as JSON Schema files

### ISSUE THREAD

**Issue by jdesrosiers** [hyperjump-io/json-schema-language-tools#5]
The server is hardcoded to identify `**/*.schema.json` and `**/schema.json` files as JSON Schema files. This setting would allow you to change that. For example, users should be able to select a directory where the client will look for schemas.

Depends on: #4

**Comment by Adity20** [comment]
Can I work on this one @jdesrosiers

**Comment by Adity20** [comment]
My partner and I would like to work on this issue. Please assign. I have created a DM group on slack with my partner to discuss and collaborate as mentioned in the qualification task requirements. Thanks. @jdesrosiers

**Comment by nikhilyadav24** [comment]
hey! @jdesrosiers please assign this to me i'll be working with @Adity20

**Comment by Adity20** [comment]
Hello @jdesrosiers 
I performed some steps to complete this task and I want to know if these were the changes you're looking for before making the pull request.
1. I added a new configuration setting for the schema directory. This will be the directory where the client looks for schema files.
2. Then I updated the configuration change handler.
3. Then I implemented the logic of identifying the json schema files.
4. In the end I handled the errors or a feedback if a specific directory doesn't exist

**Comment by Adity20** [comment]
We'll have to work on issue #4 to get more out of these changes.

**Comment by jdesrosiers** [comment]
A few things sound a bit off.

> 1. I added a new configuration setting for the schema directory. This will be the directory where the client looks for schema files.

This sounds too focused on directories. I expect something like a list of patterns that files need to match. For example, the default is `["**/*.schema.json", "**/schema.json"]` which means any file that ends with `.schema.json`. If you wanted to use `.json` extensions and and limit to a the "schemas" directory, you would set the value to `["schemas/**/*.json"]`.

> 3. Then I implemented the logic of identifying the json schema files.

I don't think you actually have to implement the logic for identifying the files. That functionality is built in. You should just need to pass in a new set of patterns. That's my expectation at least, but I could be wrong.

> 4. In the end I handled the errors or a feedback if a specific directory doesn't exist

I'm not sure I see a need for error handling. If a pattern includes a directory that doesn't exist, then nothing will match that pattern.

> We'll have to work on issue https://github.com/hyperjump-io/json-schema-language-tools/issues/4 to get more out of these changes.

Another group is working on #4 as part of their [task](https://github.com/hyperjump-io/json-schema-language-tools/pull/25). You'll need to coordinate with them.

**Comment by Adity20** [comment]
Firstly thanks for clarifying each point with such details @jdesrosiers 
I will surely look into all the things you mentioned.
I will shift my direction to patterns rather than focusing on directories.
