### ISSUE TITLE
Sever - Add config for a default dialect

### ISSUE THREAD

**Issue by jdesrosiers** [hyperjump-io/json-schema-language-tools#6]
The dialect of the schema needs to be known in order to do any sort of validation or annotation of the schema. The dialect is usually specified per schema using the `$schema` keyword. This config would specify a dialect to use if no `$schema` keyword is used.

Depends on: #4

**Comment by diyaayay** [comment]
@jdesrosiers My partner and I would like to work on this issue. Please assign. I have created a DM group on slack with my partner to discuss and collaborate as mentioned in the qualification task requirements. Thanks.

**Comment by jdesrosiers** [comment]
Great, you've been assigned. Please ask your partner to comment on the issue as well so I have their github handle and can assign them too.

**Comment by jdesrosiers** [comment]
Keep in mind that this issue depends on setting up configuration support in general (#4) and you'll have to do that as well to complete this task. But, that should be fairly trivial to get done using https://code.visualstudio.com/api/language-extensions/language-server-extension-guide as an example.

**Comment by wthrajat** [comment]
Hi @jdesrosiers! I will be collaborating with @diyaayay for this task. Also yes we understand this one and #4 are related. The config management functionality would be implemented in #4 and this issue should include settings for specifying the default schema dialect to use when the `$schema` keyword is absent.

**Comment by jdesrosiers** [comment]
Resolved by #25
