### ISSUE TITLE
Server - Validate references

### ISSUE THREAD

**Issue by jdesrosiers** [hyperjump-io/json-schema-language-tools#7]
Provide diagnostics for invalid references in a schema.

- [ ] Local references
- [ ] External references

**Comment by probablyArth** [comment]
Me and my partner, would like to work on this issue for gsoc. I have created a group DM in slack and added you!
Please assign!

**Comment by benodiwal** [comment]
Hey! I'm the partner!

**Comment by ankitkumarspj0831** [comment]
@jdesrosiers , as we were discussing on the issue https://github.com/hyperjump-io/json-schema-language-tools/issues/18, I have started working on this issue.

**Comment by jdesrosiers** [comment]
@ankitkumarspj0831 How about you join @probablyArth and @benodiwal and work as a trio? Is everyone ok with that?

**Comment by lmgyuan** [comment]
Could I still join this group? The issue #19 that I am interested in working on seems to depend on this one. Thanks in advance!
