### ISSUE TITLE
Server - Code completion for $schema

### ISSUE THREAD

**Issue by jdesrosiers** [hyperjump-io/json-schema-language-tools#9]
Provide code completion functionality for the `$schema` keyword. Get the available dialects from `@hyperjump/json-schema`.

**Comment by HodaSalim** [comment]
Hey @jdesrosiers ! I would like to take the issue and collaborate with @Azzam1503

**Comment by Azzam1503** [comment]
Hy @jdesrosiers!
I am collaborating with @HodaSalim to work on this issue, should we start working on it or do you want to have a meeting first?

**Comment by jdesrosiers** [comment]
Great! You're both assigned. You can begin work whenever you're ready. Let me know if you have questions.

**Comment by Azzam1503** [comment]
@jdesrosiers we have to create a group with you for discussion?

**Comment by jdesrosiers** [comment]
> I found that keyword.js have the methods to do with dialects, keywords and vocabularies.

:+1: 

> The API is divided into drafts(dialects)

No, the API is the same for each dialect. You use the same set of functions (API) no matter which dialect(s) you're using. Hint: The README is organized by API. Each top level heading represents an API and has a subheading called "API" that describes the available functions.

> should I have to collect the $schema keyword from each dialect endpoint or should I have to do something else.

I'm not sure what that means, but everything you need to implement the new function is in keywords.js. @HodaSalim, what do you think? Do you see how this function could be implemented?

**Comment by HodaSalim** [comment]
Hey Team,

So like Azzam I also walked through the code and played with it a bit along with the README files. 

I have a hypothesis that I didn't fully experiment yet that we can use the loadDialect function to traverse through the supported schemas. 
How we would get the supported schemas ? 
I'm not able to detect any function that does that so my thought process is to go through the draft-*/schema.js and the get the schema URI values. 

My thought process is that we need to be able to detect new added schema specifications in the future so we can use the project filing structure to determine such changes or added schemas

**Comment by Azzam1503** [comment]
I think we can import the schemas in keywords.js file and wrap them in a function and send the $shecma key for each schema version(dialect) from that function.

**Comment by HodaSalim** [comment]
I was thinking like this :

```ts
function getSchemaValues(directory:string):string[] {
      const files = fs.readdirSync(directory);
      const schemaValues = [];

   ` // Loop through each file
`    for (const file of files) {
        // Check if it's a directory
        const filePath = path.join(directory, file);
        const stats = fs.statSync(filePath);

        if (stats.isDirectory()) {
            // Recursively process subdirectories
            schemaValues.push(...getSchemaValues(filePath));
        } else if (file === 'schema.js' && directory.includes('draft-')) {
            // Extract schema value from schema.js file in draft-* directory
            const content = fs.readFileSync(filePath, 'utf8');
            const match = content.match(/"\$schema":\s*"([^"]+)"/);

            if (match) {
                schemaValues.push(match[1]);
            }
        }
    }

    return schemaValues;
}

```

**Comment by jdesrosiers** [comment]
> I have a hypothesis that I didn't fully experiment yet that we can use the getDialect function to traverse through the supported schemas.

You were on the right track here, but then you veered off somewhere else. You can get all the data your function needs from the same source that `getDialect` uses.

There are several problems with what you both are proposing, but the main problem is that it's not going to give you the right data. It would give you all the dialects there is built-in support for. That assumes that you've loaded all the built-in dialects and that there are no custom dialects loaded. If either of those assumptions doesn't hold, your list is going to have too few or too many items.

For example, I haven't loaded the OpenAPI dialects in the language server, so they shouldn't show up in the list. Even though they are built-in to the library, they can't be used unless they are loaded. All I should have to do is load those dialects in the language server and they should show up in the list without having to change `@hyperjump/json-schema`. 

Another example is that it's possible (in certain circumstances) to include a custom meta-schema in your workspace and that should show up in the list too. Dialects get loaded using the `loadDialect` function. It's used to load the built-in dialects and gets used when custom dialects are encountered as well. Your function just needs to return the list of dialects that have been loaded.

**Comment by HodaSalim** [comment]
> > I have a hypothesis that I didn't fully experiment yet that we can use the getDialect function to traverse through the supported schemas.
> 
> You were on the right track here, but then you veered off somewhere else. You can get all the data your function needs from the same source that `getDialect` uses.
> 

Yeah I doubted my solution and reverted back to a safer option or so I thought. 

So now to get back to this track of thought we can use the getDialect along with the _dialect variable to get what we need. I tested it in a test project not in LSP and it seems to be returning the expected results and even identifying schemas from just @hyperjump imports which I believe we will need to work with the server file.

My initial solution which I wasn't sure how to test properly in the beginning is just exposing the _dialect variable and testing it against getDialect function to confirm that there is nothing wrong with the results 

```js
export const loadSchemaDialect = ()=>{ 
  const isSchema  = RegExp.prototype.test.bind(/(?:\.|\/|^)schema\.json$/)
  return Object.keys(_dialects).filter(async key => await isSchema(getSchema(key)));
}
```

The issue with this solution is that sometimes it believe it returns a bit more than just the schema and that still passes the getDialect function. However I would like to test more with the validation functions in the LSP repo to see if it can filter down this issue.

![Screenshot 2024-03-07 at 1 17 55 AM](https://github.com/hyperjump-io/json-schema-language-tools/assets/63150791/c268c361-b488-4b1c-8944-ec068b988ab5)

@jdesrosiers Please let us know if I'm going on the right path with this one ?

**Comment by jdesrosiers** [comment]
Yes, that's the right idea, except I don't think the `filter` does anything useful. If it does, `hasDialect` would be a better choice. @Azzam1503, what do you think?

I was surprised to see the vocabulary schemas included for 2019-09, but it makes sense. Those schemas include a `$vocabulary` keyword even though it doesn't really make sense that they do. I think the best thing is to remove the `$vocabulary` keyword from those schemas. I'll take care of that part.

**Comment by Azzam1503** [comment]
@jdesrosiers I think `hasDialect` makes better sense here.

**Comment by HodaSalim** [comment]
Hey @jdesrosiers ,
Thank you so much for your continuous feedback :)
So should we make a PR for HyperJump with the method and proceed with the LSP task ?

**Comment by Azzam1503** [comment]
Thank you so much @jdesrosiers for your guidance on this, now we can proceed with the LSP task.
